name: manual update

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    update:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update pulls
              run: bash update.sh

            - name: Commit and push
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'update pulls'
